(function(){
"use strict";
const core=window.SystemForgeCore=window.SystemForgeCore||{};
core.HelpContent={
sections:[
{id:"start",title:"Qué es System Forge",html:"<p><b>Cámara libre:</b> conserva el objeto seleccionado para propiedades y análisis, pero no cambia target, zoom ni autoescala. <b>◎ Centrar</b> lleva la vista al seleccionado bajo demanda.</p><p><b>Móvil:</b> el mapa 3D admite giro con un dedo, pinch para zoom, botones ＋/−/◎ y pantalla completa desde el encabezado. Al elegir un cuerpo en el árbol, el cajón se cierra para dejar el objeto centrado y visible.</p><p><b>System Forge</b> es un constructor y laboratorio de dinámica orbital. Permite construir, simular, analizar y experimentar con sistemas planetarios.</p><p>Las escalas visuales no modifican la física.</p>"},
{id:"build",title:"Construir",html:"<p><b>Catálogo estelar:</b> combina <code>systems.js</code> como índice galáctico con el <code>galaxy.js</code> vigente de Voyastris. Al cargar un sistema genérico incorpora sus estrellas/componentes y, cuando existen, planetas, satélites, satélites artificiales, cometas y asteroides. Sol, Alpha Centauri y Canopus mantienen los presets detallados de System Forge.</p><p><b>Explorador del sistema:</b> sustituye al antiguo árbol como panel de navegación. Se pliega igual que Análisis, Vista y capas e Importar/exportar y permite renombrar el sistema.</p><p><b>Interfaz:</b> Crear cuerpo, Generador, Escenario y Baricentro se abren en cuadros de diálogo. En escritorio, ☰ y ⚙ muestran u ocultan los paneles laterales.</p><p><b>Árbol:</b> las ramas pueden plegarse. Las estructuras se seleccionan desde el árbol, no mediante clic en el mapa 3D.</p><p>Crea estrellas, planetas, lunas, cuerpos menores, estructuras y baricentros. <b>Las estrellas también pueden orbitar manualmente otro cuerpo o un baricentro</b>: elige padre/referencia y define a, e, i, Ω, ω y M₀. Después el N-body evoluciona el sistema.</p><p>Las estructuras representan distribuciones completas sin convertir cada punto en un cuerpo N-body.</p>"},
{id:"simulate",title:"Simular",html:"<p><b>N-body</b> integra cuerpos con masa. System Forge selecciona tres regímenes según el coste real: N-body completo; <b>N-body planetario rápido</b>, donde estrellas/planetas/menores siguen integrándose entre sí y las lunas avanzan desde su órbita osculante actual; y Kepler osculante para escalas extremas cuando la arquitectura lo permite. El cambio usa coste medido y evita que una luna de pocas horas obligue a miles de pasos globales por segundo.</p><p>La capa de órbitas puede mostrar la <b>órbita osculante actual</b> calculada desde el estado N-body, la órbita inicial o ambas. La trayectoria real es un historial separado del camino ya recorrido.</p>"},
{id:"scenarios",title:"Escenarios",html:"<p>Lanza asteroides gigantes, cometas interestelares, planetas errantes o estrellas visitantes. Los objetos entrantes usan trayectorias abiertas o estado cartesiano. Si el N-body los deja ligados a una estrella o planeta, System Forge puede materializar la captura y convertirla en una nueva órbita jerárquica.</p>"},
{id:"generator",title:"Generador de sistemas",html:"<p>El generador unificado crea estrella única, binaria o triple jerárquica y añade planetas S-type o P-type. Los límites son conservadores: conviene verificar el resultado con N-body.</p>"},
{id:"multiple",title:"Sistemas múltiples manuales",html:"<p><b>Cambios automáticos:</b> si la dinámica cambia el padre o referencia orbital de un cuerpo, Propiedades y Análisis registran origen, destino, causa y tiempo.</p><p><b>Binaria baricéntrica manual:</b> crea dos estrellas, crea un baricentro con ambas y usa <b>Configurar binaria baricéntrica</b> desde la referencia. System Forge define una única órbita relativa A–B y reparte posición/velocidad según las masas.</p><p>También puedes construirlos a mano. Pulsa <b>+ Estrella</b>, elige padre o baricentro y ajusta a/e/i/Ω/ω/M₀. Puedes repetir el proceso para arquitecturas jerárquicas. System Forge evita ciclos padre-hijo y referencias autorreferentes.</p>"},
{id:"minorBodiesHelp",title:"Clasificación de cuerpos",html:"<p><b>Cuerpo planetario:</b> planeta o planeta enano. <b>Satélite natural:</b> regular, irregular, capturado, luna pastora, coorbital o especial. <b>Cuerpo menor:</b> asteroide, cometa, meteoroide, centauro, TNO, disco disperso, NEO, troyano, damocloide, interestelar u otro. Los planetas enanos no se incluyen entre los cuerpos menores.</p><p>Los cuerpos menores usan una <b>clase principal</b>: asteroide, cometa, meteoroide, centauro, TNO, disco disperso, NEO, troyano, damocloide, objeto interestelar u otro. Varias categorías pueden solaparse en astronomía real. La clase principal se usa para organizar, filtrar y describir el objeto sin cambiar la física N-body.</p>"},
{id:"observations",title:"Datos observacionales",html:"<p><b>Etiquetas del proyecto:</b> desde ⚙ Opciones puedes crear y editar etiquetas reutilizables. Se aplican desde Propiedades y sirven para separar lore, universo, procedencia o cualquier clasificación propia.</p><p>Cada cuerpo admite estado confirmado, candidato, provisional, hipotético, discutido, refutado/retirado o modelo, además de naturaleza de masa/radio/periodo/temperatura, catálogo, método, fuente y notas.</p>"},
{id:"captures",title:"Capturas y escapes",html:"<p>Un visitante puede pasar a captura temporal y después materializada. La aplicación recalcula su órbita desde el estado N-body, cambia la jerarquía y conserva la trayectoria de entrada. Si vuelve a quedar desligado registra el escape.</p>"},
{id:"experiment",title:"Resultados del experimento",html:"<p>System Forge compara el inicio del experimento con el estado actual: Δa, Δe, Δi, energía orbital específica, momento angular específico y ranking de cuerpos perturbados. También registra series distancia-tiempo de binarias y visitantes. <b>Marcar inicio ahora</b> permite comenzar una comparación sin reiniciar la física.</p>"},
{id:"analysis",title:"Analizar",html:"<p>En escritorio, Análisis temporal y Resultados del experimento se redimensionan desde sus <b>bordes laterales/superior/inferior</b> únicamente cuando están desplegados.</p><p><b>Temporal ON/OFF</b> controla el registro temporal en vivo. Apagarlo evita el seguimiento angular, conjunciones y redibujado periódico del gráfico durante simulaciones rápidas; el botón <b>Analizar</b> bajo demanda sigue disponible.</p><p>El diagnóstico vivo detecta reestructuración orbital: S-type gravemente excitada, pérdida de vínculo con el anfitrión, posible transición P-type y candidatos a eyección.</p><p>Incluye estabilidad, Hill/Roche, MOID, resonancias, evolución secular, encuentros temporales y estadísticas de trazadores.</p>"},
{id:"concepts",title:"Conceptos",html:"<dl><dt>Excentricidad e</dt><dd>e=0 circular; 0&lt;e&lt;1 elipse; e=1 parábola; e&gt;1 hipérbola.</dd><dt>Ω</dt><dd>Longitud del nodo ascendente.</dd><dt>ω</dt><dd>Argumento de periastro.</dd><dt>MOID</dt><dd>Distancia mínima geométrica entre dos órbitas; no garantiza encuentro temporal.</dd><dt>Hill</dt><dd>Escala aproximada de dominio gravitatorio.</dd><dt>Roche</dt><dd>Escala de disrupción por mareas.</dd><dt>Libración</dt><dd>Oscilación acotada de un ángulo resonante.</dd><dt>Trazador</dt><dd>Partícula sin masa que siente gravedad pero no perturba a otros cuerpos.</dd><dt>Captura temporal</dt><dd>El objeto tiene energía orbital negativa respecto a un anfitrión durante un intervalo, pero todavía puede escapar.</dd><dt>Captura materializada</dt><dd>La condición ligada persiste y System Forge convierte el estado N-body actual en una nueva órbita ligada.</dd><dt>Órbita osculante</dt><dd>Órbita instantánea derivada de la posición y velocidad actuales. Cambia cuando otros cuerpos perturban el movimiento.</dd><dt>Trayectoria real</dt><dd>Camino que el cuerpo ya ha recorrido durante la integración N-body; no es una predicción futura.</dd><dt>Baricentro dinámico</dt><dd>Centro de masas calculado desde las posiciones físicas actuales. Se desplaza cuando se mueven sus miembros o el sistema completo.</dd></dl>"}
],
contextual:{
eccentricity:"Excentricidad: e=0 circular; 0<e<1 elipse; e=1 parábola; e>1 hipérbola.",
omega:"ω orienta el periastro dentro del plano orbital.",
Omega:"Ω orienta la línea de nodos.",
moid:"MOID es una distancia geométrica entre órbitas, no un encuentro temporal garantizado.",
tracer:"Los trazadores no tienen masa: reciben gravedad pero no aumentan el coste N² del N-body.",
cartesian:"Estado cartesiano: posición XYZ en UA y velocidad VXYZ en km/s respecto a la referencia orbital.",semimajor:"Semieje mayor a: tamaño característico de una órbita ligada. En una estrella compañera define la escala inicial de su órbita.",orbitReference:"La referencia baricéntrica hace que el cuerpo se inicialice respecto al centro de masas de varios miembros. Un cuerpo no puede orbitar un baricentro que lo contenga.",osculatingOrbit:"La órbita osculante se recalcula desde la posición y velocidad N-body actuales. Es la órbita instantánea que tendría el cuerpo si cesaran las perturbaciones en ese momento.",realTrail:"La trayectoria real guarda posiciones ya recorridas durante N-body. Es un historial, no una órbita predicha; su longitud está limitada para proteger rendimiento.",minorClass:"Clase principal de cuerpo menor usada para organización y filtros. Algunas categorías astronómicas reales se solapan."
}};
})();