import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
global.window={SystemForgeCore:{}};
require('../src/renderer/overlay-priority.js');
require('../src/renderer/marker-layer.js');
require('../src/renderer/camera-navigation.js');
const {OverlayPriorityResolver,MarkerLayer,CameraNavigation}=window.SystemForgeCore;
const earth={id:'earth',kind:'planet',parent:'sun',massEarth:1},moon={id:'moon',kind:'moon',parent:'earth',massEarth:.0123},iss={id:'iss',kind:'spacecraft',parent:'earth',massEarth:7e-20},sun={id:'sun',kind:'star',parent:null,massSolar:1};
const state={bodies:[sun,earth,moon,iss],selected:'earth',showLabels:true,labelCategories:new Set(['selected','stars','planets','moons','spacecraft'])};
const resolver=new OverlayPriorityResolver({state,categoryVisible:()=>true,isDwarfPlanet:()=>false,isCometMinor:()=>false,massSolar:b=>b.massSolar??(b.massEarth||0)*3.0034896149156e-6});
assert.ok(resolver.priority(earth)>resolver.priority(moon),'Earth host must outrank Moon');
state.selected='moon';assert.ok(resolver.priority(moon)>resolver.priority(earth),'selected Moon must outrank Earth');
assert.equal(resolver.categoryKey(earth),'planets');assert.equal(resolver.categoryKey(moon),'moons');assert.equal(resolver.categoryKey(iss),'spacecraft');assert.equal(resolver.markerCategoryVisible(moon),true);assert.equal(resolver.markerCategoryVisible(iss),true);
assert.equal(MarkerLayer.bodyFadeForDiameter(5),1);assert.ok(Math.abs(MarkerLayer.bodyFadeForDiameter(8)-.5)<1e-12);assert.equal(MarkerLayer.bodyFadeForDiameter(11),0);assert.equal(MarkerLayer.bodyFadeForDiameter(20),0);
assert.equal(CameraNavigation.easing(0),0);assert.equal(CameraNavigation.easing(1),1);assert.ok(CameraNavigation.easing(.25)<.25);assert.ok(CameraNavigation.easing(.75)>.75);
assert.equal(OverlayPriorityResolver.boxesOverlap({l:0,r:10,t:0,b:10},{l:9,r:20,t:0,b:10},0),true);
assert.equal(OverlayPriorityResolver.boxesOverlap({l:0,r:10,t:0,b:10},{l:11,r:20,t:0,b:10},0),false);
console.log('renderer-smoke OK');
