(function(){
"use strict";
const core=window.SystemForgeCore=window.SystemForgeCore||{};
core.HelpContent={
sections:[
{id:"start",title:"Qué es System Forge",html:"<p><b>System Forge</b> es un constructor y laboratorio de dinámica orbital. Permite construir, simular, analizar y experimentar con sistemas planetarios.</p><p>Las escalas visuales no modifican la física.</p>"},
{id:"build",title:"Construir",html:"<p><b>Árbol:</b> las ramas pueden plegarse. Las estructuras se seleccionan desde el árbol, no mediante clic en el mapa 3D.</p><p>Crea estrellas, planetas, lunas, cuerpos menores, estructuras y baricentros. <b>Las estrellas también pueden orbitar manualmente otro cuerpo o un baricentro</b>: elige padre/referencia y define a, e, i, Ω, ω y M₀. Después el N-body evoluciona el sistema.</p><p>Las estructuras representan distribuciones completas sin convertir cada punto en un cuerpo N-body.</p>"},
{id:"simulate",title:"Simular",html:"<p><b>N-body</b> integra cuerpos con masa. La vista <b>Kepler osculante</b> es una previsualización rápida sin perturbaciones que parte del estado físico actual, nunca de la órbita inicial. Durante escenarios con visitantes o cuerpos capturados, el modo acelerado conserva un <b>N-body planetario híbrido</b> para seguir capturas y escapes.</p><p>La capa de órbitas puede mostrar la <b>órbita osculante actual</b> calculada desde el estado N-body, la órbita inicial o ambas. La trayectoria real es un historial separado del camino ya recorrido.</p>"},
{id:"scenarios",title:"Escenarios",html:"<p>Lanza asteroides gigantes, cometas interestelares, planetas errantes o estrellas visitantes. Los objetos entrantes usan trayectorias abiertas o estado cartesiano. Si el N-body los deja ligados a una estrella o planeta, System Forge puede materializar la captura y convertirla en una nueva órbita jerárquica.</p>"},
{id:"generator",title:"Generador de sistemas",html:"<p>El generador unificado crea estrella única, binaria o triple jerárquica y añade planetas S-type o P-type. Los límites son conservadores: conviene verificar el resultado con N-body.</p>"},
{id:"multiple",title:"Sistemas múltiples manuales",html:"<p>También puedes construirlos a mano. Pulsa <b>+ Estrella</b>, elige padre o baricentro y ajusta a/e/i/Ω/ω/M₀. Puedes repetir el proceso para arquitecturas jerárquicas. System Forge evita ciclos padre-hijo y referencias autorreferentes.</p>"},
{id:"observations",title:"Datos observacionales",html:"<p>Cada cuerpo admite estado confirmado, candidato, provisional, hipotético, discutido, refutado/retirado o modelo, además de naturaleza de masa/radio/periodo/temperatura, catálogo, método, fuente y notas.</p>"},
{id:"captures",title:"Capturas y escapes",html:"<p>Un visitante puede pasar a captura temporal y después materializada. La aplicación recalcula su órbita desde el estado N-body, cambia la jerarquía y conserva la trayectoria de entrada. Si vuelve a quedar desligado registra el escape.</p>"},
{id:"analysis",title:"Analizar",html:"<p><b>Temporal ON/OFF</b> controla el registro temporal en vivo. Apagarlo evita el seguimiento angular, conjunciones y redibujado periódico del gráfico durante simulaciones rápidas; el botón <b>Analizar</b> bajo demanda sigue disponible.</p><p>El diagnóstico vivo detecta reestructuración orbital: S-type gravemente excitada, pérdida de vínculo con el anfitrión, posible transición P-type y candidatos a eyección.</p><p>Incluye estabilidad, Hill/Roche, MOID, resonancias, evolución secular, encuentros temporales y estadísticas de trazadores.</p>"},
{id:"concepts",title:"Conceptos",html:"<dl><dt>Excentricidad e</dt><dd>e=0 circular; 0&lt;e&lt;1 elipse; e=1 parábola; e&gt;1 hipérbola.</dd><dt>Ω</dt><dd>Longitud del nodo ascendente.</dd><dt>ω</dt><dd>Argumento de periastro.</dd><dt>MOID</dt><dd>Distancia mínima geométrica entre dos órbitas; no garantiza encuentro temporal.</dd><dt>Hill</dt><dd>Escala aproximada de dominio gravitatorio.</dd><dt>Roche</dt><dd>Escala de disrupción por mareas.</dd><dt>Libración</dt><dd>Oscilación acotada de un ángulo resonante.</dd><dt>Trazador</dt><dd>Partícula sin masa que siente gravedad pero no perturba a otros cuerpos.</dd><dt>Captura temporal</dt><dd>El objeto tiene energía orbital negativa respecto a un anfitrión durante un intervalo, pero todavía puede escapar.</dd><dt>Captura materializada</dt><dd>La condición ligada persiste y System Forge convierte el estado N-body actual en una nueva órbita ligada.</dd><dt>Órbita osculante</dt><dd>Órbita instantánea derivada de la posición y velocidad actuales. Cambia cuando otros cuerpos perturban el movimiento.</dd><dt>Trayectoria real</dt><dd>Camino que el cuerpo ya ha recorrido durante la integración N-body; no es una predicción futura.</dd><dt>Baricentro dinámico</dt><dd>Centro de masas calculado desde las posiciones físicas actuales. Se desplaza cuando se mueven sus miembros o el sistema completo.</dd></dl>"}
],
contextual:{
eccentricity:"Excentricidad: e=0 circular; 0<e<1 elipse; e=1 parábola; e>1 hipérbola.",
omega:"ω orienta el periastro dentro del plano orbital.",
Omega:"Ω orienta la línea de nodos.",
moid:"MOID es una distancia geométrica entre órbitas, no un encuentro temporal garantizado.",
tracer:"Los trazadores no tienen masa: reciben gravedad pero no aumentan el coste N² del N-body.",
cartesian:"Estado cartesiano: posición XYZ en UA y velocidad VXYZ en km/s respecto a la referencia orbital.",semimajor:"Semieje mayor a: tamaño característico de una órbita ligada. En una estrella compañera define la escala inicial de su órbita.",orbitReference:"La referencia baricéntrica hace que el cuerpo se inicialice respecto al centro de masas de varios miembros. Un cuerpo no puede orbitar un baricentro que lo contenga.",osculatingOrbit:"La órbita osculante se recalcula desde la posición y velocidad N-body actuales. Es la órbita instantánea que tendría el cuerpo si cesaran las perturbaciones en ese momento.",realTrail:"La trayectoria real guarda posiciones ya recorridas durante N-body. Es un historial, no una órbita predicha; su longitud está limitada para proteger rendimiento."
}};
})();