// js/squads_real.js
// Plantillas "reales" por club. Si un club aparece aquí, se usan estos jugadores
// en vez de la generación automática de data.js.
// Los atributos detallados se siguen generando en el motor a partir de overall + posición.

export const realSquads = {
  // =======================
  // ATLÉTICO DE MADRID
  // =======================
  atletico: [
    {
      id: "atletico_oblak",
      name: "Jan Oblak",
      shirtNumber: 13,
      position: "POR",
      birthDate: "1993-01-07",
      nationality: "Eslovenia",
      birthPlace: "Škofja Loka, Eslovenia",
      youthClub: "Olimpija Ljubljana",
      age: 31,
      overall: 88,
      wage: 8000000,
      contractYears: 3,
      value: 40000000
    },
    {
      id: "atletico_grbic",
      name: "Ivo Grbić",
      shirtNumber: 1,
      position: "POR",
      birthDate: "1996-01-18",
      nationality: "Croacia",
      birthPlace: "Split, Croacia",
      youthClub: "Hajduk Split",
      age: 28,
      overall: 78,
      wage: 1095120,
      contractYears: 2,
      value: 5779800
    },

    // Defensas
    {
      id: "atletico_azpilicueta",
      name: "César Azpilicueta",
      shirtNumber: 3,
      position: "LD",
      birthDate: "1989-08-28",
      nationality: "España",
      birthPlace: "Zizur Mayor, España",
      youthClub: "CA Osasuna",
      age: 35,
      overall: 80,
      wage: 1152000,
      contractYears: 1,
      value: 6080000
    },
    {
      id: "atletico_gimenez",
      name: "José María Giménez",
      shirtNumber: 2,
      position: "DFC",
      birthDate: "1995-01-20",
      nationality: "Uruguay",
      birthPlace: "Toledo, Uruguay",
      youthClub: "Danubio FC",
      age: 30,
      overall: 84,
      wage: 1270080,
      contractYears: 3,
      value: 6703200
    },
    {
      id: "atletico_savic",
      name: "Stefan Savić",
      shirtNumber: 15,
      position: "DFC",
      birthDate: "1991-01-08",
      nationality: "Montenegro",
      birthPlace: "Mojkovac, Montenegro",
      youthClub: "Brskovo Mojkovac",
      age: 34,
      overall: 82,
      wage: 1210320,
      contractYears: 2,
      value: 6387800
    },
    {
      id: "atletico_hermoso",
      name: "Mario Hermoso",
      shirtNumber: 22,
      position: "DFC",
      birthDate: "1995-06-18",
      nationality: "España",
      birthPlace: "Madrid, España",
      youthClub: "Real Madrid",
      age: 29,
      overall: 81,
      wage: 1180980,
      contractYears: 2,
      value: 6232950
    },
    {
      id: "atletico_reinildo",
      name: "Reinildo Mandava",
      shirtNumber: 23,
      position: "LI",
      birthDate: "1994-01-20",
      nationality: "Mozambique",
      birthPlace: "Beira, Mozambique",
      youthClub: "Ferroviário da Beira",
      age: 31,
      overall: 80,
      wage: 1152000,
      contractYears: 3,
      value: 6080000
    },
    {
      id: "atletico_molina",
      name: "Nahuel Molina",
      shirtNumber: 16,
      position: "LD",
      birthDate: "1997-04-06",
      nationality: "Argentina",
      birthPlace: "Embalse, Argentina",
      youthClub: "Boca Juniors",
      age: 27,
      overall: 82,
      wage: 1210320,
      contractYears: 3,
      value: 6387800
    },

    // Centro del campo
    {
      id: "atletico_koke",
      name: "Koke",
      shirtNumber: 6,
      position: "MC",
      birthDate: "1992-01-08",
      nationality: "España",
      birthPlace: "Madrid, España",
      youthClub: "Atlético de Madrid",
      age: 33,
      overall: 83,
      wage: 1240020,
      contractYears: 2,
      value: 6544550
    },
    {
      id: "atletico_depaul",
      name: "Rodrigo De Paul",
      shirtNumber: 5,
      position: "MC",
      birthDate: "1994-05-24",
      nationality: "Argentina",
      birthPlace: "Sarandí, Argentina",
      youthClub: "Racing Club",
      age: 30,
      overall: 82,
      wage: 1210320,
      contractYears: 3,
      value: 6387800
    },
    {
      id: "atletico_saul",
      name: "Saúl Ñíguez",
      shirtNumber: 8,
      position: "MC",
      birthDate: "1994-11-21",
      nationality: "España",
      birthPlace: "Elche, España",
      youthClub: "Atlético de Madrid",
      age: 30,
      overall: 80,
      wage: 1152000,
      contractYears: 2,
      value: 6080000
    },
    {
      id: "atletico_barrios",
      name: "Pablo Barrios",
      shirtNumber: 24,
      position: "MCD",
      birthDate: "2003-06-15",
      nationality: "España",
      birthPlace: "Madrid, España",
      youthClub: "Atlético de Madrid",
      age: 21,
      overall: 78,
      wage: 1095120,
      contractYears: 4,
      value: 5779800
    },
    {
      id: "atletico_lemar",
      name: "Thomas Lemar",
      shirtNumber: 11,
      position: "MCO",
      birthDate: "1995-11-12",
      nationality: "Francia",
      birthPlace: "Baie-Mahault, Guadalupe",
      youthClub: "Solidarité Scolaire",
      age: 29,
      overall: 79,
      wage: 1123380,
      contractYears: 2,
      value: 5928950
    },

    // Banda / segunda línea
    {
      id: "atletico_lino",
      name: "Samuel Lino",
      shirtNumber: 12,
      position: "EI",
      birthDate: "1999-12-23",
      nationality: "Brasil",
      birthPlace: "Santo André, Brasil",
      youthClub: "São Bernardo",
      age: 25,
      overall: 80,
      wage: 1152000,
      contractYears: 4,
      value: 6080000
    },
    {
      id: "atletico_riquelme",
      name: "Rodrigo Riquelme",
      shirtNumber: 17,
      position: "EI",
      birthDate: "2000-04-02",
      nationality: "España",
      birthPlace: "Madrid, España",
      youthClub: "Atlético de Madrid",
      age: 25,
      overall: 79,
      wage: 1123380,
      contractYears: 4,
      value: 5928950
    },

    // Delanteros / segundas puntas
    {
      id: "atletico_griezmann",
      name: "Antoine Griezmann",
      shirtNumber: 7,
      position: "SD",
      birthDate: "1991-03-21",
      nationality: "Francia",
      birthPlace: "Mâcon, Francia",
      youthClub: "Real Sociedad",
      age: 34,
      overall: 86,
      wage: 8000000,
      contractYears: 2,
      value: 28000000
    },
    {
      id: "atletico_morata",
      name: "Álvaro Morata",
      shirtNumber: 9,
      position: "DC",
      birthDate: "1992-10-23",
      nationality: "España",
      birthPlace: "Madrid, España",
      youthClub: "Real Madrid",
      age: 33,
      overall: 83,
      wage: 1240020,
      contractYears: 2,
      value: 6544550
    },
    {
      id: "atletico_correa",
      name: "Ángel Correa",
      shirtNumber: 10,
      position: "SD",
      birthDate: "1995-03-09",
      nationality: "Argentina",
      birthPlace: "Rosario, Argentina",
      youthClub: "San Lorenzo",
      age: 30,
      overall: 81,
      wage: 1180980,
      contractYears: 3,
      value: 6232950
    },
    {
      id: "atletico_memphis",
      name: "Memphis Depay",
      shirtNumber: 19,
      position: "DC",
      birthDate: "1994-02-13",
      nationality: "Países Bajos",
      birthPlace: "Moordrecht, Países Bajos",
      youthClub: "Sparta Rotterdam",
      age: 31,
      overall: 82,
      wage: 1210320,
      contractYears: 2,
      value: 6387800
    },
    {
      id: "atletico_samu",
      name: "Samu Omorodion",
      shirtNumber: 20,
      position: "DC",
      birthDate: "2004-05-05",
      nationality: "España",
      birthPlace: "Melilla, España",
      youthClub: "Granada CF",
      age: 21,
      overall: 77,
      wage: 1067220,
      contractYears: 4,
      value: 5632550
    }
  ],

  // =======================
  // REAL MADRID CF
  // =======================
  realmadrid: [
    // Porteros
    {
      id: "realmadrid_courtois",
      name: "Thibaut Courtois",
      shirtNumber: 1,
      position: "POR",
      birthDate: "1992-05-11",
      nationality: "Bélgica",
      birthPlace: "Bree, Bélgica",
      youthClub: "Genk",
      age: 33,
      overall: 89,
      wage: 9000000,
      contractYears: 3,
      value: 45000000
    },
    {
      id: "realmadrid_lunin",
      name: "Andriy Lunin",
      shirtNumber: 13,
      position: "POR",
      birthDate: "1999-02-11",
      nationality: "Ucrania",
      birthPlace: "Krasnohrad, Ucrania",
      youthClub: "Dnipro",
      age: 26,
      overall: 80,
      wage: 3000000,
      contractYears: 3,
      value: 18000000
    },

    // Defensas
    {
      id: "realmadrid_carvajal",
      name: "Dani Carvajal",
      shirtNumber: 2,
      position: "LD",
      birthDate: "1992-01-11",
      nationality: "España",
      birthPlace: "Leganés, España",
      youthClub: "Real Madrid",
      age: 33,
      overall: 83,
      wage: 6500000,
      contractYears: 2,
      value: 22000000
    },
    {
      id: "realmadrid_mendy",
      name: "Ferland Mendy",
      shirtNumber: 23,
      position: "LI",
      birthDate: "1995-06-08",
      nationality: "Francia",
      birthPlace: "Meulan-en-Yvelines, Francia",
      youthClub: "Paris Saint-Germain",
      age: 30,
      overall: 82,
      wage: 5500000,
      contractYears: 2,
      value: 26000000
    },
    {
      id: "realmadrid_alaba",
      name: "David Alaba",
      shirtNumber: 4,
      position: "DFC",
      birthDate: "1992-06-24",
      nationality: "Austria",
      birthPlace: "Viena, Austria",
      youthClub: "Austria Viena",
      age: 33,
      overall: 84,
      wage: 9000000,
      contractYears: 2,
      value: 26000000
    },
    {
      id: "realmadrid_militao",
      name: "Éder Militão",
      shirtNumber: 3,
      position: "DFC",
      birthDate: "1998-01-18",
      nationality: "Brasil",
      birthPlace: "Sertãozinho, Brasil",
      youthClub: "São Paulo",
      age: 27,
      overall: 85,
      wage: 7500000,
      contractYears: 3,
      value: 40000000
    },
    {
      id: "realmadrid_rudiger",
      name: "Antonio Rüdiger",
      shirtNumber: 22,
      position: "DFC",
      birthDate: "1993-03-03",
      nationality: "Alemania",
      birthPlace: "Berlín, Alemania",
      youthClub: "VfB Stuttgart",
      age: 32,
      overall: 84,
      wage: 8000000,
      contractYears: 2,
      value: 28000000
    },

    // Centro del campo
    {
      id: "realmadrid_camavinga",
      name: "Eduardo Camavinga",
      shirtNumber: 6,
      position: "MCD",
      birthDate: "2002-11-10",
      nationality: "Francia",
      birthPlace: "Miconje, Angola",
      youthClub: "Stade Rennais",
      age: 23,
      overall: 83,
      wage: 6000000,
      contractYears: 4,
      value: 45000000
    },
    {
      id: "realmadrid_tchouameni",
      name: "Aurélien Tchouaméni",
      shirtNumber: 18,
      position: "MCD",
      birthDate: "2000-01-27",
      nationality: "Francia",
      birthPlace: "Rouen, Francia",
      youthClub: "Girondins de Bordeaux",
      age: 25,
      overall: 84,
      wage: 6500000,
      contractYears: 4,
      value: 50000000
    },
    {
      id: "realmadrid_valverde",
      name: "Fede Valverde",
      shirtNumber: 15,
      position: "MC",
      birthDate: "1998-07-22",
      nationality: "Uruguay",
      birthPlace: "Montevideo, Uruguay",
      youthClub: "Peñarol",
      age: 27,
      overall: 86,
      wage: 7500000,
      contractYears: 4,
      value: 65000000
    },
    {
      id: "realmadrid_bellingham",
      name: "Jude Bellingham",
      shirtNumber: 5,
      position: "MCO",
      birthDate: "2003-06-29",
      nationality: "Inglaterra",
      birthPlace: "Stourbridge, Inglaterra",
      youthClub: "Birmingham City",
      age: 22,
      overall: 88,
      wage: 9000000,
      contractYears: 5,
      value: 90000000
    },
    {
      id: "realmadrid_kroos",
      name: "Toni Kroos",
      shirtNumber: 8,
      position: "MC",
      birthDate: "1990-01-04",
      nationality: "Alemania",
      birthPlace: "Greifswald, Alemania",
      youthClub: "Hansa Rostock",
      age: 35,
      overall: 85,
      wage: 10000000,
      contractYears: 1,
      value: 15000000
    },
    {
      id: "realmadrid_modric",
      name: "Luka Modrić",
      shirtNumber: 10,
      position: "MC",
      birthDate: "1985-09-09",
      nationality: "Croacia",
      birthPlace: "Zadar, Croacia",
      youthClub: "Dinamo Zagreb",
      age: 39,
      overall: 84,
      wage: 9000000,
      contractYears: 1,
      value: 8000000
    },

    // Banda / ataque
    {
      id: "realmadrid_vinicius",
      name: "Vinícius Jr.",
      shirtNumber: 7,
      position: "EI",
      birthDate: "2000-07-12",
      nationality: "Brasil",
      birthPlace: "São Gonçalo, Brasil",
      youthClub: "Flamengo",
      age: 25,
      overall: 89,
      wage: 11000000,
      contractYears: 4,
      value: 110000000
    },
    {
      id: "realmadrid_rodrygo",
      name: "Rodrygo",
      shirtNumber: 11,
      position: "ED",
      birthDate: "2001-01-09",
      nationality: "Brasil",
      birthPlace: "Osasco, Brasil",
      youthClub: "Santos",
      age: 24,
      overall: 85,
      wage: 7000000,
      contractYears: 4,
      value: 65000000
    },
    {
      id: "realmadrid_guler",
      name: "Arda Güler",
      shirtNumber: 24,
      position: "MCO",
      birthDate: "2005-02-25",
      nationality: "Turquía",
      birthPlace: "Altındağ (Ankara), Turquía",
      youthClub: "Gençlerbirliği",
      age: 20,
      overall: 80,
      wage: 3000000,
      contractYears: 5,
      value: 25000000
    },

    // Delanteros
    {
      id: "realmadrid_mbappe",
      name: "Kylian Mbappé",
      shirtNumber: 9,
      position: "DC",
      birthDate: "1998-12-20",
      nationality: "Francia",
      birthPlace: "Bondy, Francia",
      youthClub: "AS Bondy",
      age: 27,
      overall: 91,
      wage: 20000000,
      contractYears: 5,
      value: 160000000
    },
    {
      id: "realmadrid_endrick",
      name: "Endrick",
      shirtNumber: 16,
      position: "DC",
      birthDate: "2006-07-21",
      nationality: "Brasil",
      birthPlace: "Brasilia, Brasil",
      youthClub: "Palmeiras",
      age: 19,
      overall: 79,
      wage: 2500000,
      contractYears: 5,
      value: 30000000
    }
  ],

  // =======================
  // FC BARCELONA
  // =======================
  barcelona: [
    // Porteros
    {
      id: "barcelona_terstegen",
      name: "Marc-André ter Stegen",
      shirtNumber: 1,
      position: "POR",
      birthDate: "1992-04-30",
      nationality: "Alemania",
      birthPlace: "Mönchengladbach, Alemania",
      youthClub: "Borussia Mönchengladbach",
      age: 33,
      overall: 88,
      wage: 9000000,
      contractYears: 3,
      value: 40000000
    },
    {
      id: "barcelona_inaki",
      name: "Iñaki Peña",
      shirtNumber: 13,
      position: "POR",
      birthDate: "1999-03-02",
      nationality: "España",
      birthPlace: "Alicante, España",
      youthClub: "FC Barcelona",
      age: 26,
      overall: 78,
      wage: 2000000,
      contractYears: 3,
      value: 12000000
    },

    // Defensas
    {
      id: "barcelona_kounde",
      name: "Jules Koundé",
      shirtNumber: 23,
      position: "DFC",
      birthDate: "1998-11-12",
      nationality: "Francia",
      birthPlace: "París, Francia",
      youthClub: "Girondins de Bordeaux",
      age: 27,
      overall: 84,
      wage: 6500000,
      contractYears: 4,
      value: 50000000
    },
    {
      id: "barcelona_araujo",
      name: "Ronald Araújo",
      shirtNumber: 4,
      position: "DFC",
      birthDate: "1999-03-07",
      nationality: "Uruguay",
      birthPlace: "Rivera, Uruguay",
      youthClub: "Rentistas",
      age: 26,
      overall: 86,
      wage: 8000000,
      contractYears: 4,
      value: 65000000
    },
    {
      id: "barcelona_cristensen",
      name: "Andreas Christensen",
      shirtNumber: 15,
      position: "DFC",
      birthDate: "1996-04-10",
      nationality: "Dinamarca",
      birthPlace: "Lillerød, Dinamarca",
      youthClub: "Brøndby IF",
      age: 29,
      overall: 83,
      wage: 5000000,
      contractYears: 3,
      value: 30000000
    },
    {
      id: "barcelona_cancelo",
      name: "João Cancelo",
      shirtNumber: 2,
      position: "LD",
      birthDate: "1994-05-27",
      nationality: "Portugal",
      birthPlace: "Barreiro, Portugal",
      youthClub: "Benfica",
      age: 31,
      overall: 84,
      wage: 7000000,
      contractYears: 2,
      value: 30000000
    },
    {
      id: "barcelona_balde",
      name: "Alejandro Balde",
      shirtNumber: 3,
      position: "LI",
      birthDate: "2003-10-18",
      nationality: "España",
      birthPlace: "Barcelona, España",
      youthClub: "FC Barcelona",
      age: 22,
      overall: 81,
      wage: 2500000,
      contractYears: 4,
      value: 35000000
    },

    // Centro del campo
    {
      id: "barcelona_dejong",
      name: "Frenkie de Jong",
      shirtNumber: 21,
      position: "MC",
      birthDate: "1997-05-12",
      nationality: "Países Bajos",
      birthPlace: "Gorinchem, Países Bajos",
      youthClub: "Willem II",
      age: 28,
      overall: 86,
      wage: 9000000,
      contractYears: 4,
      value: 70000000
    },
    {
      id: "barcelona_pedri",
      name: "Pedri",
      shirtNumber: 8,
      position: "MC",
      birthDate: "2002-11-25",
      nationality: "España",
      birthPlace: "Tegueste (Tenerife), España",
      youthClub: "UD Las Palmas",
      age: 22,
      overall: 87,
      wage: 8000000,
      contractYears: 5,
      value: 90000000
    },
    {
      id: "barcelona_gavi",
      name: "Gavi",
      shirtNumber: 6,
      position: "MC",
      birthDate: "2004-08-05",
      nationality: "España",
      birthPlace: "Los Palacios y Villafranca, España",
      youthClub: "Real Betis",
      age: 21,
      overall: 84,
      wage: 5000000,
      contractYears: 5,
      value: 60000000
    },
    {
      id: "barcelona_gundogan",
      name: "İlkay Gündoğan",
      shirtNumber: 5,
      position: "MC",
      birthDate: "1990-10-24",
      nationality: "Alemania",
      birthPlace: "Gelsenkirchen, Alemania",
      youthClub: "VfL Bochum",
      age: 35,
      overall: 85,
      wage: 8000000,
      contractYears: 2,
      value: 18000000
    },
    {
      id: "barcelona_fermin",
      name: "Fermín López",
      shirtNumber: 16,
      position: "MCO",
      birthDate: "2003-05-11",
      nationality: "España",
      birthPlace: "El Campillo (Huelva), España",
      youthClub: "Real Betis",
      age: 22,
      overall: 80,
      wage: 2000000,
      contractYears: 4,
      value: 25000000
    },

    // Banda / ataque
    {
      id: "barcelona_raphinha",
      name: "Raphinha",
      shirtNumber: 11,
      position: "ED",
      birthDate: "1996-12-14",
      nationality: "Brasil",
      birthPlace: "Porto Alegre, Brasil",
      youthClub: "Avaí",
      age: 28,
      overall: 84,
      wage: 6000000,
      contractYears: 4,
      value: 45000000
    },
    {
      id: "barcelona_lewandowski",
      name: "Robert Lewandowski",
      shirtNumber: 9,
      position: "DC",
      birthDate: "1988-08-21",
      nationality: "Polonia",
      birthPlace: "Varsovia, Polonia",
      youthClub: "Varsovia Varsovia",
      age: 37,
      overall: 86,
      wage: 11000000,
      contractYears: 2,
      value: 20000000
    },
    {
      id: "barcelona_felix",
      name: "João Félix",
      shirtNumber: 14,
      position: "SD",
      birthDate: "1999-11-10",
      nationality: "Portugal",
      birthPlace: "Viseu, Portugal",
      youthClub: "Benfica",
      age: 26,
      overall: 83,
      wage: 6000000,
      contractYears: 3,
      value: 35000000
    },
    {
      id: "barcelona_yamal",
      name: "Lamine Yamal",
      shirtNumber: 27,
      position: "ED",
      birthDate: "2007-07-13",
      nationality: "España",
      birthPlace: "Esplugues de Llobregat, España",
      youthClub: "FC Barcelona",
      age: 18,
      overall: 84,
      wage: 3000000,
      contractYears: 5,
      value: 80000000
    },
    {
      id: "barcelona_ferran",
      name: "Ferran Torres",
      shirtNumber: 7,
      position: "EI",
      birthDate: "2000-02-29",
      nationality: "España",
      birthPlace: "Foios, España",
      youthClub: "Valencia CF",
      age: 25,
      overall: 82,
      wage: 5000000,
      contractYears: 3,
      value: 35000000
    }
  ]
};
