(function(){
"use strict";
const core=window.SystemForgeCore=window.SystemForgeCore||{};
core.HelpContent={
sections:[
{id:"start",title:"Qué es System Forge",html:"<p><b>System Forge</b> es simultáneamente un simulador astronómico independiente y una herramienta de autoría de sistemas para Voyastris. El mismo núcleo físico sirve para construir, simular, perturbar, analizar y validar sistemas.</p><p><b>Selección y cámara:</b> puedes seleccionar desde el Explorador, directamente sobre el cuerpo 3D o mediante los anillos de posición 1:1. Desde ⚙ Opciones puedes activar un <b>viaje progresivo</b> al seleccionado y elegir su duración. Cámara libre conserva la selección sin obligarte a seguir el objetivo.</p><p><b>Escala 3D:</b> el recorrido es <b>1:1 → Adapt. → Local</b>. En 1:1 las distancias y radios son físicos. Los anillos de posición ayudan a localizar cuerpos demasiado pequeños sin inflarlos; desaparecen a medida que el cuerpo alcanza tamaño visible.</p>"},
{id:"interface",title:"Interfaz y navegación",html:"<p><b>Móvil:</b> el layout móvil se conserva al girar vertical ↔ horizontal. Los paneles laterales siguen funcionando como drawers y los controles táctiles no deberían convertirse en la interfaz de escritorio.</p><p><b>⚙ Opciones:</b> permite mostrar/ocultar Zoom móvil, Centrar, Seguir/Libre, Análisis temporal, panel de rendimiento e iconos 1:1. También configura el viaje progresivo de cámara y su duración.</p><p><b>Hover astronómico:</b> al pasar el ratón por un astro o por su anillo 1:1 aparece una ficha compacta con tipo, masa, radio y datos orbitales disponibles. No selecciona ni mueve la cámara.</p><p><b>Botones divididos:</b> Órbitas, Trayectoria N-body y Etiquetas usan un botón principal para mostrar/ocultar la capa y un subbotón ▾ para sus opciones. Solo permanece abierto un submenú a la vez.</p>"},
{id:"build",title:"Construir sistemas",html:"<p>Las herramientas principales son <b>Crear cuerpo</b>, <b>Generador</b>, <b>Escenario</b>, <b>Baricentro</b>, <b>Medir A↔B</b> y <b>Catálogo estelar</b>.</p><p>El Explorador del sistema muestra la jerarquía completa. Puedes crear estrellas, cuerpos planetarios, satélites naturales, <b>vehículos espaciales</b>, cuerpos menores, estructuras y referencias virtuales. Las estrellas pueden orbitar un cuerpo o un baricentro; el N-body evoluciona después la arquitectura.</p><p>Las estructuras representan cinturones, nubes y anillos como un objeto lógico con muchos puntos, evitando convertir cada partícula en un cuerpo N-body.</p>"},
{id:"catalog",title:"Catálogo Voyastris",html:"<p><b>systems.js</b> proporciona el índice/posición galáctica y <b>galaxy.js</b> aporta el contenido interno: estrellas/componentes, planetas, satélites, satélites artificiales, cometas y asteroides.</p><p>Sol, Alpha Centauri y Canopus abren modelos detallados de System Forge para no degradar su dinámica. Los sistemas genéricos usan la instantánea local validada de Voyastris.</p><p>Las masas que no constan en la fuente no se presentan como medidas reales: se usan masa 0 o placeholders explícitos cuando son necesarios para una jerarquía.</p>"},
{id:"simulate",title:"Simular",html:"<p>El núcleo N-body usa integración tipo Velocity Verlet. System Forge selecciona el régimen apropiado según timestep y coste: <b>N-body completo</b>, <b>N-body planetario rápido</b> con lunas osculantes y <b>Kepler osculante</b> para escalas extremas cuando la arquitectura lo permite.</p><p>La trayectoria real N-body es un historial del camino ya recorrido. La órbita osculante es la órbita instantánea deducida de posición y velocidad actuales; no son lo mismo.</p><p>Capturas, cambios de padre, escapes y visitantes se calculan a partir del estado dinámico, no como animaciones prefijadas.</p>"},
{id:"scaleCamera",title:"Escala, iconos y cámara",html:"<p><b>1:1:</b> radios y distancias son físicos. <b>Adapt.:</b> recupera la legibilidad visual. <b>Local:</b> amplifica el entorno jerárquico del seleccionado. Cambiar escala nunca modifica el estado N-body.</p><p><b>Anillos de posición:</b> aparecen alrededor de cuerpos demasiado pequeños, son clicables y comienzan a desvanecerse cuando el astro supera 5 px de diámetro aparente. Si varios se solapan, usan la misma prioridad que las etiquetas: seleccionado primero y después el cuerpo jerárquicamente más importante; por ejemplo, Tierra prevalece sobre Luna salvo que Luna esté seleccionada.</p><p><b>Viaje de cámara:</b> al seleccionar un objeto puede iniciarse una transición suave desde la posición actual. Arrastrar, hacer zoom o Centrar cancela el viaje. En Cámara libre, el viaje no cambia el modo al terminar.</p>"},
{id:"layers",title:"Vista y capas",html:"<p><b>Órbitas ▾</b>: elige Contextuales, Todas o Solo seleccionada y decide si ves geometría osculante actual, inicial/nominal o ambas.</p><p><b>Trayectoria N-body ▾</b>: selecciona Solo seleccionado, Contextual, Todos o Desactivada y ajusta el historial a 150, 300, 600 o 1.200 muestras. Desde v1.9.4.4 el muestreo y el refresco se adaptan a la velocidad del simulador y al movimiento del astro; el extremo visible permanece unido a su posición actual.</p><p><b>Etiquetas ▾</b>: combina Seleccionado, Estrellas, Planetas, Planetas enanos, Satélites, <b>Vehículos espaciales</b>, Cuerpos menores y Cometas. Si se solapan, prevalece primero el seleccionado y después el cuerpo jerárquicamente más importante. Los anillos 1:1 reutilizan este mismo criterio.</p>"},
{id:"scenarios",title:"Escenarios y encuentros",html:"<p>Las plantillas actuales incluyen asteroide gigante, cometa interestelar, planeta errante, estrella visitante y Gliese 710. Gliese 710 es una <b>plantilla de encuentro</b>, no un preset duplicado del Sistema Solar.</p><p>Los objetos entrantes usan estado orbital/cartesiano real dentro del N-body. Si quedan ligados, System Forge puede materializar una captura y reconstruir la nueva jerarquía desde el estado dinámico actual.</p>"},
{id:"generator",title:"Generador de sistemas",html:"<p>El generador puede usar el sistema actual o crear una estrella única, binaria o triple jerárquica. Los planetas pueden generarse S-type o P-type según el anfitrión.</p><p>Es un <b>generador de arquitecturas plausibles</b>, no un modelo completo de formación planetaria. Sus resultados deben verificarse con las herramientas de estabilidad y N-body.</p>"},
{id:"multiple",title:"Binarias, triples y baricentros",html:"<p>Los baricentros son referencias virtuales: no añaden masa por sí mismos. En una binaria, System Forge puede definir una órbita relativa A–B y repartir posición/velocidad según las masas.</p><p>Las jerarquías manuales permiten estrellas y cuerpos orbitando referencias distintas. Los cambios automáticos de padre/referencia se registran cuando la dinámica indica captura, transición o pérdida de vínculo.</p>"},
{id:"classification",title:"Clasificación y etiquetas",html:"<p><b>Cuerpo planetario:</b> planeta o planeta enano. <b>Satélite natural:</b> regular, irregular, capturado, pastor, coorbital o especial. <b>Cuerpo menor:</b> asteroide, cometa, meteoroide, centauro, TNO, disco disperso, NEO, troyano, damocloide, interestelar u otro. <b>Vehículo espacial:</b> satélite artificial, sonda, nave tripulada, estación, módulo de aterrizaje, rover, observatorio, carga, repetidor u otro objeto artificial.</p><p>Las etiquetas base del proyecto son <b>CF</b> (Ciencia Ficción), <b>Dune</b> y <b>Voyastris</b>. Los IDs internos históricos se conservan para compatibilidad con proyectos anteriores. Puedes crear cualquier etiqueta adicional desde ⚙ Opciones.</p>"},
{id:"measurement",title:"Medir A↔B e inspector relativo",html:"<p><b>Medir A↔B</b> convierte dos cuerpos cualesquiera en un instrumento dinámico. Elige A y B desde los selectores o arma <b>A ← selección</b>/<b>B ← selección</b> y pulsa un astro en el Explorador, el 3D o un anillo 1:1.</p><p>El panel se actualiza durante la simulación y muestra <b>distancia, tiempo-luz, velocidad relativa, radial y tangencial, energía orbital específica, momento angular específico y estado ligado/no ligado</b>. Cuando existe masa gravitatoria suficiente calcula además a/e/i, periapsis, apoapsis y periodo relativos.</p><p>La línea A↔B usa las mismas posiciones visuales que el render, por lo que respeta 1:1, Adapt. y Local sin alterar la física. Puedes ocultar la línea o su etiqueta de distancia y centrar A o B sin cambiar el par medido.</p>"},
{id:"spacecraft",title:"Vehículos espaciales",html:"<p>Desde <b>Crear cuerpo → Vehículo espacial</b> puedes añadir satélites artificiales, sondas, naves tripuladas, estaciones, landers, rovers, observatorios, carga, repetidores u otros vehículos. Tienen clase, misión, operador, masa seca, propelente, tamaño, tripulación y propulsión.</p><p>En <b>Spacecraft I</b> son cuerpos <b>balísticos</b>: sienten la gravedad y participan en N-body/fast-time, pero todavía no ejecutan empuje, maniobras, consumo de propelente, drag atmosférico ni reboost. Esas funciones pertenecen a Spacecraft II.</p><p>El preset Solar incluye ISS, Hubble, Parker Solar Probe, Voyager 1 y Voyager 2 como casos de referencia. Los estados de órbita baja derivados de TLE se usan como condiciones iniciales aproximadas; Voyager y Parker documentan explícitamente cuándo el estado es un modelo y no una efeméride exacta.</p>"},
{id:"observations",title:"Datos y procedencia",html:"<p>Cada cuerpo admite estado confirmado, candidato, provisional, hipotético, discutido, retirado o modelo; además puede registrar naturaleza de masa/radio/periodo/temperatura, catálogo, método, fuente, epoch y notas.</p><p>Los sistemas importados desde Voyastris conservan <code>sourceFields</code> para no perder información original. Los valores ausentes se marcan como desconocidos, modelo o placeholder en lugar de presentarse como medidas.</p>"},
{id:"experiment",title:"Experimentos y análisis",html:"<p><b>Medir A↔B</b> permite inspección relativa instantánea sin iniciar un experimento. <b>Análisis temporal</b> registra la evolución en vivo cuando está ON. Puede ocultarse completamente desde Opciones. El análisis bajo demanda sigue disponible aunque el registro en vivo esté apagado.</p><p><b>Resultados del experimento</b> compara baseline y estado actual: Δa, Δe, Δi, energía orbital específica, momento angular específico y ranking de perturbaciones.</p><p><b>Rendimiento:</b> el HUD de FPS puede ocultarse desde Opciones. Las métricas internas continúan funcionando porque el cambio automático de régimen físico necesita medir el coste real aunque el panel no se vea.</p><p><b>Análisis del sistema</b> reúne estabilidad, Hill/Roche, cruces, resonancias, cuerpos menores, satélites, jerarquía, encuentros, eventos, dinámica avanzada y verificación N-body.</p>"},
{id:"concepts",title:"Conceptos",html:"<dl><dt>Excentricidad e</dt><dd>e=0 circular; 0&lt;e&lt;1 elipse; e=1 parábola; e&gt;1 hipérbola.</dd><dt>Ω</dt><dd>Longitud del nodo ascendente.</dd><dt>ω</dt><dd>Argumento de periastro.</dd><dt>MOID</dt><dd>Distancia mínima geométrica entre dos órbitas; no garantiza encuentro temporal.</dd><dt>Hill</dt><dd>Escala aproximada del dominio gravitatorio de un cuerpo.</dd><dt>Roche</dt><dd>Escala de disrupción por mareas.</dd><dt>Libración</dt><dd>Oscilación acotada de un ángulo resonante.</dd><dt>Trazador</dt><dd>Partícula sin masa que siente gravedad pero no perturba a otros cuerpos.</dd><dt>Órbita osculante</dt><dd>Órbita instantánea derivada de posición y velocidad actuales.</dd><dt>Trayectoria real</dt><dd>Camino ya recorrido durante la integración N-body.</dd><dt>Baricentro</dt><dd>Centro de masas de un conjunto de cuerpos; puede usarse como referencia orbital.</dd><dt>CF</dt><dd>Etiqueta base de Ciencia Ficción; puede combinarse con Dune, Voyastris u otras etiquetas del proyecto.</dd></dl>"}
],
contextual:{
eccentricity:"Excentricidad: e=0 circular; 0<e<1 elipse; e=1 parábola; e>1 hipérbola.",
omega:"ω orienta el periastro dentro del plano orbital.",
Omega:"Ω orienta la línea de nodos.",
moid:"MOID es una distancia geométrica entre órbitas, no un encuentro temporal garantizado.",
tracer:"Los trazadores no tienen masa: reciben gravedad pero no aumentan el coste N² del N-body.",
cartesian:"Estado cartesiano: posición XYZ en UA y velocidad VXYZ en km/s respecto a la referencia orbital.",
semimajor:"Semieje mayor a: tamaño característico de una órbita ligada.",
orbitReference:"Una referencia baricéntrica inicializa el cuerpo respecto al centro de masas de varios miembros. Un cuerpo no puede orbitar una referencia que lo contenga.",
osculatingOrbit:"La órbita osculante se recalcula desde posición y velocidad N-body actuales: es la órbita instantánea si cesaran las perturbaciones en ese momento.",
realTrail:"La trayectoria real guarda posiciones ya recorridas durante N-body. Es un historial, no una predicción futura; su longitud está limitada para proteger rendimiento.",
minorClass:"Clase principal de cuerpo menor usada para organización y filtros. Algunas categorías astronómicas reales se solapan."
}};
})();
